name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages 2
        env:
            COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "$COMMIT_MESSAGES"
      - name: "contains #skip"
        if: ${{ contains(env.COMMIT_MESSAGES, '#skip') }}
        env:
            COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "#skip in $COMMIT_MESSAGES"
      - name: "does not contains #skip"
        if: ${{ !contains(env.COMMIT_MESSAGES, '#skip') }}
        env:
            COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "#skip not in  $COMMIT_MESSAGES"
      - name: "contains #skip v.2"
        if: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
        run: echo "#skip"
      - name: "does not contains #skip v.2"
        if: ${{ !contains(toJson(github.event.commits.*.message), '#skip') }}
        run: echo "not \#skip"